[build]
  publish = "public"
  command = "composer install && npm install && php artisan migrate && npm run build"

[context.production.environment]
  PHP_VERSION = "8.3"

[build.environment]
  COMPOSER_ALLOW_SUPERUSER = "1"
  COMPOSER_MEMORY_LIMIT = "-1"

[[plugins]]
  package = "netlify-plugin-php"

[plugins.inputs]
  extensions = ["pgsql", "pdo_pgsql"]
